version: '3'
services:

  #PHP Service
  app:
    build:
      context: ./ip2-frontend
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./ip2-frontend:/var/www
      - ./ip2-frontend/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ip2-frontend:/var/www
      - ./ip2-frontend/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ip2_frontend
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./ip2-frontend/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  #Heartbeat service
  heartbeat:
    build:
      context: ./Heartbeat
      dockerfile: Dockerfile
    container_name: heartbeat
    restart: unless-stopped
    stdin_open: true
    tty: true
    working_dir: /usr/src/app
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local