# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ main ]
    
jobs:
  laravel:
    name: Laravel (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-20.04
    env:
      working-directory: ./ip2-frontend 
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4']
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4'
    - uses: actions/checkout@v2
    - name: Copy .env
      working-directory: ${{env.working-directory}}
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      working-directory: ${{env.working-directory}}
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    # - name: Generate key
    #   working-directory: ${{env.working-directory}}
    #   run: php artisan key:generate
    - name: Directory Permissions
      working-directory: ${{env.working-directory}}
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      working-directory: ${{env.working-directory}}
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      working-directory: ${{env.working-directory}}
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: laravel
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: bash startup.sh
